"""add late_days to borrow records

Revision ID: 41c7223bb11f
Revises: fa01f78cfb2d
Create Date: 2026-08-03 18:24:34.958230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41c7223bb11f'
down_revision: Union[str, Sequence[str], None] = 'fa01f78cfb2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('borrow_records', sa.Column('late_days', sa.BigInteger(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('borrow_records', 'late_days')
    # ### end Alembic commands ###
